name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: |
        cd src/
        dotnet restore
    - name: Test
      run: |
        cd src/
        dotnet test

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build package for Release
      env:
        VERSION: ${{ GITHUB_RUN_NUMBER }}
      run: |
        cd src/
        dotnet pack -c Release
    - name: Push package to nuget
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      run: dotnet nuget push **/SmartHead.Reports.*.nupkg -k $NUGET_KEY -s https://www.nuget.org/api/v2/package --skip-duplicate
